/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#f8f9ff',
        surface: '#f8f9ff',
        'surface-dim': '#ccdbf2',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eef4ff',
        'surface-container': '#e5efff',
        'surface-container-high': '#dbe9ff',
        'surface-container-highest': '#d4e4fa',
        'on-surface': '#0d1c2d',
        'on-surface-variant': '#3d4a3e',
        'inverse-surface': '#233143',
        'inverse-on-surface': '#e9f1ff',
        outline: '#6d7b6d',
        'outline-variant': '#bccabb',
        'surface-tint': '#006d36',
        primary: '#006d36',
        'on-primary': '#ffffff',
        'primary-container': '#4ade80',
        'on-primary-container': '#005e2d',
        'inverse-primary': '#4de082',
        secondary: '#545f73',
        'on-secondary': '#ffffff',
        'secondary-container': '#d5e0f8',
        'on-secondary-container': '#586377',
        tertiary: '#5c5f61',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#c2c4c6',
        'on-tertiary-container': '#4e5153',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        // Legacy brand alias mappings
        brand: {
          primary: '#006d36',
          'primary-container': '#4ade80',
          'on-primary-container': '#005e2d',
          surface: '#ffffff',
          background: '#f8f9ff',
          'on-background': '#0d1c2d',
          'on-surface-variant': '#3d4a3e',
          'surface-container-low': '#eef4ff',
          'surface-container': '#e5efff',
          'surface-container-high': '#dbe9ff',
          slate: '#0d1c2d',
          secondary: '#545f73',
          outline: '#6d7b6d',
          'outline-variant': '#bccabb',
        },
      },
      borderRadius: {
        'DEFAULT': '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px',
        'card': '24px',
        'pill': '9999px',
      },
      spacing: {
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '16px',
        'margin-mobile': '20px',
        'margin-desktop': '48px',
      },
      fontFamily: {
        outfit: ['Outfit', 'sans-serif'],
        jakarta: ['Plus Jakarta Sans', 'sans-serif'],
        'display-lg': ['Outfit', 'sans-serif'],
        'headline-lg': ['Outfit', 'sans-serif'],
        'headline-md': ['Outfit', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'label-bold': ['Plus Jakarta Sans', 'sans-serif'],
        'label-md': ['Plus Jakarta Sans', 'sans-serif'],
      },
      boxShadow: {
        'zenith-soft': '0px 4px 20px rgba(13, 28, 45, 0.05)',
        'zenith-card': '0px 8px 30px rgba(13, 28, 45, 0.08)',
        'zenith-floating': '0px 12px 36px rgba(0, 109, 54, 0.2)',
      },
    },
  },
  plugins: [],
};

